# -*- coding: utf-8 -*-
"""Natural Language Processing Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dn1Ay2vNQSnobtZ2TTjcC3ilpz47DgBd
"""

# Commented out IPython magic to ensure Python compatibility.
# Text Preprocessing & Cleaning
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS
from nltk import SnowballStemmer
from sklearn.model_selection import train_test_split # Split Data
from imblearn.over_sampling import SMOTE # Handling Imbalanced
import string
import pandas as pd
import numpy as np
import tweepy
import re
from textblob import TextBlob
from collections import namedtuple
# Model Building
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score # Performance Metrics
# Data Visualization
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

data = pd.read_excel("Sentiment GOTO.xlsx")
data.head(10)

# Ambil kolom 'created_at' dan 'full_text'
tweet_data = data[['created_at', 'full_text','retweet_count']]

# Ubah DataFrame menjadi list of dictionaries
tweet_list = tweet_data.to_dict('records')

print(type(tweet_list))

"""Natural Language Processing for Sentiment Categorization"""

hasil_analisis = []
for tweet in tweet_list:
  tweet_properties = {}
  tweet_properties["tanggal_tweet"] = tweet["created_at"]  # Gunakan key "created_at"
  tweet_properties["isi_tweet"] = tweet["full_text"]  # Gunakan key "full_text"
  tweet_bersih = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",tweet["full_text"]).split())

  analysis = TextBlob(tweet_bersih)
  if analysis.sentiment.polarity > 0.0:
    tweet_properties["sentiment"] = "positif"
  elif analysis.sentiment.polarity == 0.0:
    tweet_properties["sentiment"] = "netral"
  else:
    tweet_properties["sentiment"] = "negatif"

  if tweet['retweet_count'] >0 :
    if tweet_properties not in hasil_analisis:
      hasil_analisis.append(tweet_properties)
  else:
    hasil_analisis.append(tweet_properties)

hasil_analisis_df = pd.DataFrame(hasil_analisis)
hasil_analisis_df

tweet_positif = [t for t in hasil_analisis if t["sentiment"]=="positif"]
tweet_netral = [t for t in hasil_analisis if t["sentiment"]=="netral"]
tweet_negatif = [t for t in hasil_analisis if t["sentiment"]=="negatif"]

print("Hasil Sentimen")
print("positif: ",len(tweet_positif), "({} %)".format(100*len(tweet_positif)/len(hasil_analisis)))
print("netral: ",len(tweet_netral), "({} %)".format(100*len(tweet_netral)/len(hasil_analisis)))
print("negatif: ",len(tweet_negatif), "({} %)".format(100*len(tweet_negatif)/len(hasil_analisis)))

"""Data Pre-Processing for Modelling"""

tweet_data['full_text'] = tweet_data['full_text'].str.replace('https\S+', ' ', case=False)
tweet_data['full_text'] = tweet_data['full_text'].str.lower()
tweet_data['full_text'] = tweet_data['full_text'].str.replace('@\S+', ' ', case=False)
tweet_data['full_text'] = tweet_data['full_text'].str.replace('#\S+', ' ', case=False)
tweet_data['full_text'] = tweet_data['full_text'].str.replace("\'\w+", ' ', case=False)
tweet_data['full_text'] = tweet_data['full_text'].str.replace("[^\w\s]", ' ', case=False)
tweet_data['full_text'] = tweet_data['full_text'].str.replace("\s(2)", ' ', case=False)

# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize
#df['content']=df.apply(lambda row: nltk.word_tokenize(row['content']), axis=1)
from nltk.tokenize import RegexpTokenizer
regexp = RegexpTokenizer('\w+')
tweet_data['content_token']=tweet_data['full_text'].apply(regexp.tokenize)
tweet_data.head(3)

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
# Make a list of Indonesian stopwords
stopwords = nltk.corpus.stopwords.words("indonesian")
# Extend the list with your own custom stopwords
my_stopwords = ['goto']
stopwords.extend(my_stopwords)
# Remove stopwords
tweet_data['content_token'] = tweet_data['content_token'].apply(lambda x: [item for item in x if item not in stopwords])
tweet_data.head(3)

!pip install Sastrawi

# import Sastrawi package
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()
tweet_data['stemmed'] = tweet_data['content_token'].apply(lambda x: [stemmer.stem(y) for y in x]) # Stem every word.
tweet_data.head(5)

tweet_data['text_string'] = tweet_data['stemmed'].apply(lambda x: ' '.join([item for item in x if len(item)>3]))
tweet_data.head(5)

tweet_data['text_string'] = tweet_data['text_string'].astype('str')
tweet_data['text_string'] = tweet_data['text_string'].astype(pd.StringDtype())
tweet_data

# Gabungkan kolom 'sentiment' dari hasil_analisis_df ke tweet_data berdasarkan indeks
tweet_data = pd.concat([tweet_data, hasil_analisis_df['sentiment']], axis=1)
tweet_data

# Simpan DataFrame ke file Excel dengan nama sheet "Data"
tweet_data.to_excel('tweet data GOTO cleaned.xlsx', sheet_name='Data', index=False)

"""Wordcloud"""

!pip install wordcloud

# Commented out IPython magic to ensure Python compatibility.
tweet_data_p=tweet_data[tweet_data['sentiment']=="positif"]
all_words_lem = ' '.join([word for word in tweet_data_p['text_string']])
# %matplotlib inline
import matplotlib.pyplot as plt
from wordcloud import WordCloud
wordcloud = WordCloud(background_color='white', width=800, height=500, random_state=21, max_font_size=130).generate(all_words_lem)
plt.figure(figsize=(20, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off');

# Commented out IPython magic to ensure Python compatibility.
tweet_data_neg=tweet_data[tweet_data['sentiment']=="negatif"]
all_words_lemneg = ' '.join([word for word in tweet_data_neg['text_string']])
# %matplotlib inline
import matplotlib.pyplot as plt
from wordcloud import WordCloud
wordcloud = WordCloud(background_color='white', width=800, height=500, random_state=21, max_font_size=130).generate(all_words_lemneg)
plt.figure(figsize=(20, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off');

# Commented out IPython magic to ensure Python compatibility.
tweet_data_net=tweet_data[tweet_data['sentiment']=="netral"]
all_words_lemnet = ' '.join([word for word in tweet_data_net['text_string']])
# %matplotlib inline
import matplotlib.pyplot as plt
from wordcloud import WordCloud
wordcloud = WordCloud(background_color='white', width=800, height=500, random_state=21, max_font_size=130).generate(all_words_lemnet)
plt.figure(figsize=(20, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off');

"""TF-IDF Vectorizer"""

X = tweet_data['text_string']
y = tweet_data['sentiment']
tfid = TfidfVectorizer()
X_final =  tfid.fit_transform(X)

"""Handling Imbalanced using SMOTE"""

smote = SMOTE()
x_sm,y_sm = smote.fit_resample(X_final,y)

"""Splitting Data"""

X_train , X_test , y_train , y_test = train_test_split(x_sm , y_sm , test_size=0.25,random_state=3)

"""Random Forest Classifier"""

random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(X_train,y_train)
random_forest_classifier_prediction =  random_forest_classifier.predict(X_test)
accuracy_score(random_forest_classifier_prediction,y_test)

# Confusion Matrix
cm = confusion_matrix(y_test, random_forest_classifier_prediction)

# Plot Confusion Matrix using Seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negatif', 'Netral', 'Positif'], yticklabels=['Negatif', 'Netral', 'Positif'])
plt.title('Random Forest Classifier Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Gradien Boosting Classifier"""

gradien_boosting_classifier = GradientBoostingClassifier()
gradien_boosting_classifier.fit(X_train,y_train)
gradien_boosting_classifier_prediction =  gradien_boosting_classifier.predict(X_test)
accuracy_score(gradien_boosting_classifier_prediction,y_test)

# Confusion Matrix
cm = confusion_matrix(y_test, gradien_boosting_classifier_prediction)

# Plot Confusion Matrix using Seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negatif', 'Netral', 'Positif'], yticklabels=['Negatif', 'Netral', 'Positif'])
plt.title('Gradient Boosting Classifier Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Multilayer Perceptron (MLP) (Feedforward Artificial Neural Network Model)"""

neural_network_classifier = MLPClassifier(hidden_layer_sizes=(128, 64), activation='relu', solver='adam', max_iter=1000)
neural_network_classifier.fit(X_train,y_train)
neural_network_classifier_prediction =  neural_network_classifier.predict(X_test)
accuracy_score(neural_network_classifier_prediction,y_test)

# Confusion Matrix
cm = confusion_matrix(y_test, neural_network_classifier_prediction)

# Plot Confusion Matrix using Seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negatif', 'Netral', 'Positif'], yticklabels=['Negatif', 'Netral', 'Positif'])
plt.title('Multilayer Perceptron (Neural Network) Classifier Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Learning Curves for Each Model"""

train_sizes, train_scores, valid_scores = learning_curve(
    RandomForestClassifier(), X_train, y_train, cv=5, n_jobs=-1, train_sizes=np.linspace(0.1, 1.0, 10))

plt.plot(train_sizes, np.mean(train_scores, axis=1), 'o-', color="r", label="Training score")
plt.plot(train_sizes, np.mean(valid_scores, axis=1), 'o-', color="g", label="Cross-validation score")

plt.xlabel("Training examples")
plt.ylabel("Score")
plt.title("Random Forest Classifier Learning Curve")
plt.legend(loc="best")
plt.show()

train_sizes, train_scores, valid_scores = learning_curve(
    GradientBoostingClassifier(), X_train, y_train, cv=5, n_jobs=-1, train_sizes=np.linspace(0.1, 1.0, 10))

plt.plot(train_sizes, np.mean(train_scores, axis=1), 'o-', color="r", label="Training score")
plt.plot(train_sizes, np.mean(valid_scores, axis=1), 'o-', color="g", label="Cross-validation score")

plt.xlabel("Training examples")
plt.ylabel("Score")
plt.title("Gradient Boosting Classifier Learning Curve")
plt.legend(loc="best")
plt.show()

"""Multilayer Perceptron (MLP) Learning Curve"""

train_sizes, train_scores, valid_scores = learning_curve(
    neural_network_classifier, X_train, y_train, cv=5, n_jobs=-1, train_sizes=np.linspace(0.1, 1.0, 10))

# Plot learning curve
plt.plot(train_sizes, np.mean(train_scores, axis=1), 'o-', color="r", label="Training score")
plt.plot(train_sizes, np.mean(valid_scores, axis=1), 'o-', color="g", label="Cross-validation score")

plt.xlabel("Training examples")
plt.ylabel("Score")
plt.title("Multilayer Perceptron (Neural Network) Classifier Learning Curve")
plt.legend(loc="best")
plt.show()